# Generated by Django 4.1 on 2022-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_baby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
