# Generated by Django 4.1 on 2022-08-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_baby_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
