# Generated by Django 4.1 on 2022-08-11 03:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_baby_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
    ]
